### ISSUE TITLE
新制作的产品包要依赖已经部署的mysql服务，如何取到已经部署的mysql实例的IP? sql初始化实例，需要有mysql客户端

### ISSUE THREAD

**Issue by lishijiang** [DTStack/chengying-schema#4]
1、schema.yml中添加继承于已经部署的mysql服务mysql@Mysql.mysql@optional，在安装向导中，发现此服务实例的ip是127.0.0.1，如何自动获取到真正的mysql实例地址？
2、定义的伪节点用于初始化数据库相关操作，发现必须要部署在mysql服务节点，才能找到客户端命令文件？

**Comment by yqhy0718** [comment]
可以用新5.7.38的mysql产品包，mysql@Mysql.mysql@optional这个是没问题的，也可以手动配置mysql的ip；
5.7.35的包，需要使用mysql@MYSQL.mysql@optional

**Comment by yqhy0718** [comment]
定义的数据库初始化操作，可以在自定义的产品包中增加一个mysql客户端，post_deploy脚本中指定mysql客户端，也可以增加判断逻辑，优先使用当前产品包中客户端，如果没有，在使用mysql包中的客户端
